
CREATE DATABASE EDUCATIVA;
GO

USE EDUCATIVA;
GO

SELECT * FROM PROGRAMA;
GO

INSERT INTO PROGRAMA(IDPROGRAMA,NOMBRE,FECINICIO)
VALUES(4,'PROGRAMADOR DE BASE DE DATOS','20210319');
GO

SELECT * FROM ALUMNO;
GO

INSERT INTO ALUMNO(NOMBRE) VALUES('KARLA LOPEZ');
GO


SELECT * FROM MATRICULA;
GO

INSERT INTO MATRICULA(FECHA,IDPROGRAMA,IDALUMNO)
VALUES( GETDATE(),4,1);
GO


SELECT * FROM CURSO;
GO

INSERT INTO CURSO(NOMBRE) VALUES('DISEÑO DE BASE DE DATOS');
INSERT INTO CURSO(NOMBRE) VALUES('SQL SERVER NIVEL I');
INSERT INTO CURSO(NOMBRE) VALUES('SQL SERVER NIVEL II');
INSERT INTO CURSO(NOMBRE) VALUES('SQL SERVER NIVEL III');
INSERT INTO CURSO(NOMBRE) VALUES('SQL SERVER NIVEL IV');
GO


SELECT * FROM DETALLE;
GO

INSERT INTO DETALLE(IDMATRICULA,MES,IDCURSO,PROFESOR) VALUES(1,1,1,'JULIO');
INSERT INTO DETALLE(IDMATRICULA,MES,IDCURSO,PROFESOR) VALUES(1,2,2,'GUSTAVO');
INSERT INTO DETALLE(IDMATRICULA,MES,IDCURSO,PROFESOR) VALUES(1,3,3,'SERGIO');
INSERT INTO DETALLE(IDMATRICULA,MES,IDCURSO,PROFESOR) VALUES(1,4,4,'LAURA');
INSERT INTO DETALLE(IDMATRICULA,MES,IDCURSO,PROFESOR) VALUES(1,5,5,'DELIA');
GO

